### PR TITLE
feat: add banners for ai readme

### PR DESCRIPTION
**Pull request by saimonkat**
This PR brings new banners for AI examples README files

Previews:
[Hybrid Search Chatbot](https://github.com/neondatabase/examples/blob/c1e331c505b5eb18c8e270e0a80cf53aeea2ad7f/ai/hybrid-search-nextjs/README.md)
[Chat with PDF (OpenAI + LangChain)](https://github.com/neondatabase/examples/blob/c1e331c505b5eb18c8e270e0a80cf53aeea2ad7f/ai/langchain/chat-with-pdf-nextjs/README.md)
[AI Chatbot (OpenAI + LangChain)](https://github.com/neondatabase/examples/blob/c1e331c505b5eb18c8e270e0a80cf53aeea2ad7f/ai/langchain/chatbot-nextjs/README.md)
[RAG Chatbot (OpenAI + LangChain)](https://github.com/neondatabase/examples/blob/c1e331c505b5eb18c8e270e0a80cf53aeea2ad7f/ai/langchain/rag-nextjs/README.md)
[Semantic Search Chatbot (OpenAI + LangChain)](https://github.com/neondatabase/examples/blob/c1e331c505b5eb18c8e270e0a80cf53aeea2ad7f/ai/langchain/semantic-search-nextjs/README.md)
[Chat with PDF (OpenAI + LlamaIndex)](https://github.com/neondatabase/examples/blob/c1e331c505b5eb18c8e270e0a80cf53aeea2ad7f/ai/llamaindex/chat-with-pdf-nextjs/README.md)
[AI Chatbot (OpenAI + LlamaIndex)](https://github.com/neondatabase/examples/blob/c1e331c505b5eb18c8e270e0a80cf53aeea2ad7f/ai/llamaindex/chatbot-nextjs/README.md)
[RAG Chatbot (OpenAI + LlamaIndex)](https://github.com/neondatabase/examples/blob/c1e331c505b5eb18c8e270e0a80cf53aeea2ad7f/ai/llamaindex/rag-nextjs/README.md)
[Reverse Image Search (OpenAI + LlamaIndex)](https://github.com/neondatabase/examples/blob/c1e331c505b5eb18c8e270e0a80cf53aeea2ad7f/ai/llamaindex/reverse-image-search-nextjs/README.md)
[Semantic Search Chatbot (OpenAI + LlamaIndex)](https://github.com/neondatabase/examples/blob/c1e331c505b5eb18c8e270e0a80cf53aeea2ad7f/ai/llamaindex/semantic-search-nextjs/README.md)

### CODE REVIEW

**Comment by saimonkat** [comment]
Hi guys @rishi-raj-jain @danieltprice 

Can somebody help me with revew and approve for this PR? 🙏

**Comment by rishi-raj-jain** [comment]
Hey @saimonkat,

I've requested for changes with the team.

**Comment by saimonkat** [comment]
@rishi-raj-jain @danieltprice hi, unique banners without buttons are updates for each of 10 pages

Please review and approve at your convenience

**Comment by rishi-raj-jain** [comment]
> @rishi-raj-jain @danieltprice hi, unique banners without buttons are updates for each of 10 pages
> 
> Please review and approve at your convenience

Pardon another ask but here's what I asked for:

"Just wanted to know if the banners were uploaded to the PR's README? If so, can we instead write a banner.<format> file in the repo while locally referencing it? This allows us to reference the images without lost paths on GH when GH assets go down.

If it's not too much of an ask."

image

**Comment by saimonkat** [comment]
@rishi-raj-jain yes right, I uploaded images to README to not expanding repo size. Sure, I'll try plaid them with images files in assets, no problem. You have a point!

**Comment by saimonkat** [comment]
@rishi-raj-jain updated according your request, please check

**Review by danieltprice — APPROVED** [review]

**Pull request merged**
